baseURL = "/blog/"
publishDir = "../blog"
title = "Blog"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.ru]
    languageName = "Русский"
    weight = 2


# IMPORTANT: publish into repo-root /blog


[permalinks]
  posts = "/:slug/"
